name: Report Parser

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          # User defined upload name. Visible in Codecov UI
          name: # optional
          # Repository upload token - get it from codecov.io. Required only for private repositories
          token: # optional
          # Path to coverage file to upload
          file: # optional
          # Comma-separated list of files to upload
          files: # optional
          # Directory to search for coverage reports.
          directory: # optional
          # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
          flags: # optional
          # Write upload file to path before uploading
          path_to_write_report: # optional
          # Environment variables to tag the upload with (e.g. PYTHON | OS,PYTHON)
          env_vars: # optional
          # Specify whether or not CI build should fail if Codecov runs into an error during upload
          fail_ci_if_error: # optional
      - name: Success job message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ✅ <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"><u>#${{ github.workflow }}</u></a>
            <b>Build:</b> ${{ github.run_number }}
            <b>Status:</b> SUCCESS

            The ${{ github.event_name }} event triggered by ${{ github.actor }}
      - name: Failure job message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            ❌ <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"><u>#${{ github.workflow }}</u></a>
            <b>Build:</b> ${{ github.run_number }}
            <b>Status:</b> FAILURE

            The ${{ github.event_name }} event triggered by ${{ github.actor }}
      - name: Cancelled job message
        if: ${{ cancelled() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: html
          message: |
            🛑 <a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"><u>#${{ github.workflow }}</u></a>
            <b>Build:</b> ${{ github.run_number }}
            <b>Status:</b> CANCELLED

            The ${{ github.event_name }} event triggered by ${{ github.actor }}

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]
